import React, { useEffect, useState } from 'react';
import { doc, getDoc, serverTimestamp, setDoc } from 'firebase/firestore';
import { ElectionAnalyticsDashboard } from './ElectionAnalytics';
import { GOOGLE_SHEETS_DATABASE } from './googleSheetsConfig';
import { auth, db } from './firebase-init';
import { loadElectionData, resetElectionVotes, setElectionPolling } from './electionApi';

const SESSION_KEY = 'ansar-election-analytics-key';
const CONFIG_REF = ['electionAdminConfig', 'primary'];
const OFFICIAL_LIVE_URL = 'https://ansarschool.in/election/live';

export default function AdminElection() {
  const [keyInput, setKeyInput] = useState(() => window.sessionStorage.getItem(SESSION_KEY) || '');
  const [analyticsKey, setAnalyticsKey] = useState(() => window.sessionStorage.getItem(SESSION_KEY) || '');
  const [showKey, setShowKey] = useState(false);
  const [loadingKey, setLoadingKey] = useState(true);
  const [savingKey, setSavingKey] = useState(false);
  const [message, setMessage] = useState('');
  const [error, setError] = useState('');
  const [pollOpen, setPollOpen] = useState(null);
  const [changingPoll, setChangingPoll] = useState(false);
  const [resettingPoll, setResettingPoll] = useState(false);
  const [analyticsVersion, setAnalyticsVersion] = useState(0);
  const sheetUrl = `https://docs.google.com/spreadsheets/d/${GOOGLE_SHEETS_DATABASE.spreadsheetId}/edit`;
  const shareUrl = analyticsKey ? `${OFFICIAL_LIVE_URL}?key=${encodeURIComponent(analyticsKey)}` : '';
  const shareText = shareUrl ? `Ansar School Election 2026 — private live analytics: ${shareUrl}` : '';

  useEffect(() => {
    let active = true;
    getDoc(doc(db, ...CONFIG_REF)).then((snapshot) => {
      const savedKey = snapshot.exists() ? String(snapshot.data().analyticsKey || '').trim() : '';
      if (active && savedKey) {
        setKeyInput(savedKey);
        setAnalyticsKey(savedKey);
        window.sessionStorage.setItem(SESSION_KEY, savedKey);
      }
    }).catch((loadError) => {
      if (active) setError(loadError.code === 'permission-denied' ? 'Your admin email must be verified before the saved analytics key can be loaded.' : 'The saved analytics key could not be loaded. You can enter it below.');
    }).finally(() => active && setLoadingKey(false));
    return () => { active = false; };
  }, []);

  useEffect(() => {
    if (!analyticsKey) return;
    loadElectionData().then((election) => setPollOpen(Boolean(election.isOpen))).catch(() => setPollOpen(null));
  }, [analyticsKey]);

  const saveAndLoadAnalytics = async (event) => {
    event.preventDefault();
    const value = keyInput.trim();
    setError('');
    setMessage('');
    if (!/^[a-zA-Z0-9_-]{20,128}$/.test(value)) {
      setError('Enter the valid analytics key generated by Apps Script.');
      return;
    }
    const email = auth.currentUser?.email || '';
    setSavingKey(true);
    try {
      await setDoc(doc(db, ...CONFIG_REF), {
        analyticsKey: value,
        updatedAt: serverTimestamp(),
        updatedBy: email
      });
      window.sessionStorage.setItem(SESSION_KEY, value);
      setAnalyticsKey(value);
      setMessage('Analytics key saved securely for authorized admins.');
    } catch (saveError) {
      setError(saveError.code === 'permission-denied' ? 'Permission denied. Sign in with a verified authorized admin email.' : (saveError.message || 'The analytics key could not be saved.'));
    } finally {
      setSavingKey(false);
    }
  };

  const copyLink = async () => {
    await navigator.clipboard.writeText(shareUrl);
    setMessage('Private live-view link copied.');
    window.setTimeout(() => setMessage(''), 2500);
  };

  const shareLink = async () => {
    if (navigator.share) {
      await navigator.share({ title: 'Ansar School Election 2026 — Live Analytics', text: 'Private live election campaign analytics for authorized officials.', url: shareUrl });
    } else {
      await copyLink();
    }
  };

  const togglePolling = async () => {
    if (!analyticsKey || changingPoll || pollOpen == null) return;
    const nextValue = !pollOpen;
    const action = nextValue ? 'OPEN' : 'CLOSE';
    if (!window.confirm(`${action} online campaign voting now? Existing votes and candidates will not be deleted.`)) return;
    setChangingPoll(true);
    setError('');
    setMessage('');
    try {
      const result = await setElectionPolling(analyticsKey, nextValue);
      setPollOpen(Boolean(result.isOpen));
      setMessage(`Online voting is now ${result.isOpen ? 'OPEN' : 'CLOSED'}.`);
    } catch (toggleError) {
      setError(toggleError.message || 'Voting status could not be changed. Deploy the latest Apps Script version and try again.');
    } finally {
      setChangingPoll(false);
    }
  };

  const resetPollAnalytics = async () => {
    if (!analyticsKey || resettingPoll) return;
    const confirmed = window.confirm('Permanently delete every recorded election vote and reset all analytics to zero? Candidates, settings and polling status will be preserved. This cannot be undone.');
    if (!confirmed) return;
    setResettingPoll(true);
    setError('');
    setMessage('');
    try {
      const result = await resetElectionVotes(analyticsKey);
      setAnalyticsVersion((version) => version + 1);
      setMessage(`Poll analytics reset successfully. ${result.clearedVotes || 0} test vote${result.clearedVotes === 1 ? '' : 's'} cleared. All previous voters can now vote again.`);
    } catch (resetError) {
      setError(resetError.message || 'Poll analytics could not be reset. Deploy the latest Apps Script version and try again.');
    } finally {
      setResettingPoll(false);
    }
  };

  return (
    <div className="space-y-7">
      <section className="rounded-2xl border border-indigo-200 bg-gradient-to-br from-indigo-950 to-violet-900 p-6 text-white shadow-lg">
        <p className="text-xs font-extrabold uppercase tracking-[0.18em] text-amber-300">School Election 2026</p>
        <h2 className="mt-2 text-2xl font-black">Campaign poll control centre</h2>
        <p className="mt-3 max-w-3xl text-sm font-medium leading-6 text-indigo-100">Candidates and positions are maintained in Google Sheets. Votes accumulate daily and remain stored until the election; this dashboard never resets totals at midnight.</p>
        <a href={sheetUrl} target="_blank" rel="noreferrer" className="mt-5 inline-flex rounded-xl bg-white px-5 py-3 text-sm font-extrabold text-indigo-800 transition hover:bg-indigo-50">Open election spreadsheet</a>
      </section>

      <section className={`rounded-2xl border p-6 shadow-sm ${pollOpen ? 'border-emerald-200 bg-emerald-50' : 'border-rose-200 bg-rose-50'}`}>
        <div className="flex flex-col gap-5 sm:flex-row sm:items-center sm:justify-between">
          <div>
            <p className={`text-xs font-extrabold uppercase tracking-[0.18em] ${pollOpen ? 'text-emerald-700' : 'text-rose-700'}`}>Emergency voting control</p>
            <h3 className="mt-2 text-xl font-black text-slate-900">Online voting is {pollOpen == null ? 'loading…' : pollOpen ? 'ON' : 'OFF'}</h3>
            <p className="mt-2 max-w-2xl text-sm font-medium leading-6 text-slate-600">Turn voting off whenever required and turn it back on later. This changes only the voting status; accumulated totals, candidates and daily vote history remain saved.</p>
          </div>
          <button type="button" role="switch" aria-checked={Boolean(pollOpen)} aria-label="Toggle online election voting" disabled={!analyticsKey || pollOpen == null || changingPoll} onClick={togglePolling} className={`relative h-14 w-28 shrink-0 rounded-full p-1.5 shadow-inner transition disabled:cursor-not-allowed disabled:opacity-50 ${pollOpen ? 'bg-emerald-600' : 'bg-slate-400'}`}>
            <span className={`grid h-11 w-11 place-items-center rounded-full bg-white text-[10px] font-black shadow-md transition-transform ${pollOpen ? 'translate-x-14 text-emerald-700' : 'translate-x-0 text-slate-600'}`}>{changingPoll ? '…' : pollOpen ? 'ON' : 'OFF'}</span>
          </button>
        </div>
      </section>

      <section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm">
        <div className="flex flex-wrap items-start justify-between gap-3">
          <div>
            <h3 className="text-lg font-black text-slate-900">Live analytics access</h3>
            <p className="mt-2 max-w-3xl text-sm font-medium leading-6 text-slate-500">Enter the Apps Script analytics key once. It is stored in an admin-only Firestore document and automatically loaded for authorized administrators.</p>
          </div>
          {analyticsKey && <span className="rounded-full bg-emerald-100 px-3 py-1.5 text-xs font-extrabold text-emerald-700">Connected</span>}
        </div>
        <form onSubmit={saveAndLoadAnalytics} className="mt-4 flex flex-col gap-3 lg:flex-row">
          <div className="relative min-w-0 flex-1">
            <input type={showKey ? 'text' : 'password'} value={keyInput} onChange={(event) => setKeyInput(event.target.value)} placeholder={loadingKey ? 'Loading saved key…' : 'Election analytics key'} disabled={loadingKey || savingKey} autoComplete="off" className="w-full rounded-xl border border-slate-300 px-4 py-3 pr-20 font-mono text-sm outline-none focus:ring-2 focus:ring-indigo-500 disabled:bg-slate-100" />
            <button type="button" onClick={() => setShowKey((value) => !value)} className="absolute inset-y-0 right-3 text-xs font-extrabold text-indigo-700">{showKey ? 'Hide' : 'Show'}</button>
          </div>
          <button disabled={loadingKey || savingKey} className="rounded-xl bg-indigo-700 px-5 py-3 font-extrabold text-white hover:bg-indigo-800 disabled:opacity-60">{savingKey ? 'Saving…' : analyticsKey ? 'Update key & load' : 'Save key & load'}</button>
        </form>
        {error && <p role="alert" className="mt-3 rounded-xl bg-red-50 px-4 py-3 text-sm font-bold text-red-700">{error}</p>}
        {message && <p role="status" className="mt-3 rounded-xl bg-emerald-50 px-4 py-3 text-sm font-bold text-emerald-700">{message}</p>}

        {shareUrl && (
          <div className="mt-6 rounded-2xl border border-indigo-100 bg-indigo-50/60 p-4">
            <div className="flex flex-wrap items-center justify-between gap-2"><h4 className="font-black text-slate-900">Share private live view with officials</h4><span className="text-xs font-bold text-slate-500">Read-only · refreshes every 10 seconds</span></div>
            <input readOnly value={shareUrl} aria-label="Private official live analytics link" className="mt-3 w-full rounded-xl border border-indigo-100 bg-white px-4 py-3 text-sm font-semibold text-slate-600 outline-none" />
            <div className="mt-3 flex flex-wrap gap-2">
              <button type="button" onClick={copyLink} className="rounded-lg bg-slate-900 px-4 py-2.5 text-sm font-bold text-white">Copy link</button>
              <button type="button" onClick={shareLink} className="rounded-lg bg-indigo-700 px-4 py-2.5 text-sm font-bold text-white">Share</button>
              <a href={`https://wa.me/?text=${encodeURIComponent(shareText)}`} target="_blank" rel="noreferrer" className="rounded-lg bg-emerald-600 px-4 py-2.5 text-sm font-bold text-white">WhatsApp</a>
              <a href={`mailto:?subject=${encodeURIComponent('Ansar School Election 2026 — Live Analytics')}&body=${encodeURIComponent(shareText)}`} className="rounded-lg border border-slate-300 bg-white px-4 py-2.5 text-sm font-bold text-slate-700">Email</a>
              <a href={shareUrl} target="_blank" rel="noreferrer" className="rounded-lg border border-indigo-300 bg-white px-4 py-2.5 text-sm font-bold text-indigo-700">Open live view</a>
            </div>
            <p className="mt-3 text-xs font-semibold leading-5 text-amber-800">Anyone who receives this private link can view the live totals. Share it only with authorized school officials.</p>
          </div>
        )}
      </section>

      <section className="rounded-2xl border border-amber-200 bg-amber-50 p-5 text-sm font-medium leading-6 text-amber-950">
        <strong className="block font-black">Candidate sheet columns</strong>
        Add one row per student in <code>electionCandidates</code>: id, section, position, name, className, photoUrl, symbolName, symbolUrl, manifesto, audience, order and active. Use exactly “Middle Section”, “Secondary Section” or “Senior Secondary Section” in the section column, and set active to TRUE.
      </section>

      <section className="rounded-2xl border border-red-200 bg-red-50 p-6 shadow-sm">
        <div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between">
          <div>
            <p className="text-xs font-extrabold uppercase tracking-[0.18em] text-red-700">Testing cleanup</p>
            <h3 className="mt-2 text-lg font-black text-slate-900">Reset poll analytics</h3>
            <p className="mt-2 max-w-2xl text-sm font-medium leading-6 text-slate-600">Delete all test votes and return totals, devices, daily activity and audience analytics to zero. All previous voters will be allowed to vote again. Candidates and poll settings are not changed.</p>
          </div>
          <button type="button" onClick={resetPollAnalytics} disabled={!analyticsKey || resettingPoll} className="shrink-0 rounded-xl bg-red-700 px-5 py-3 text-sm font-extrabold text-white transition hover:bg-red-800 disabled:cursor-not-allowed disabled:opacity-50">
            {resettingPoll ? 'Resetting…' : 'Reset test votes'}
          </button>
        </div>
      </section>

      <ElectionAnalyticsDashboard key={analyticsVersion} analyticsKey={analyticsKey} compact />
    </div>
  );
}
