import React, { useEffect, useState } from 'react';
import { deleteElectionCandidate, loadElectionData, saveElectionCandidate } from './electionApi';
import ElectionSymbolIcon, { ELECTION_SYMBOLS } from './ElectionSymbolIcon';

const ROSTER = [
  ['naeema-kathoon','Senior Secondary Section','Naeema Kathoon','12E','Puzzle Piece','Head Girl'], ['aathikah-jinan','Senior Secondary Section','Aathikah Jinan','12A','Scales of Justice','Head Girl'], ['miyaz-musthafa','Senior Secondary Section','Miyaz Musthafa','12F','Football','Head Boy'],
  ['zaya-zakharia','Secondary Section','Zaya Zakharia','XH','Clock'], ['rahmath-bari-pm','Secondary Section','Rahmath Bari P M','XF','Bridge'], ['rayan-mohamed','Secondary Section','Rayan Mohamed','XG','Microphone'], ['eshan-mohammed-ms','Secondary Section','Eshan Mohammed M S','XD','Key'],
  ['sanvi-k-nair','Middle Section','Sanvi K Nair','8-C','Microphone'], ['azza-aathif','Middle Section','Azza Aathif','8A','Light Bulb'], ['diya-nishar','Middle Section','Diya Nishar','8 C','Phoenix'], ['fateh-mohammed-azeen','Middle Section','Fateh Mohammed Azeen','8 F','Lion'], ['muhammed-al-fazza-kf','Middle Section','Muhammed Al Fazza K.F','8 B','Football'], ['mohammed-shayaan','Middle Section','Mohammed Shayaan','8 H','Spectacles'],
  ['nota-middle-section-leader','Middle Section','NOTA (None of the Above)','','NOTA','Section Leader',99],
  ['nota-secondary-section-leader','Secondary Section','NOTA (None of the Above)','','NOTA','Section Leader',99],
  ['nota-senior-head-boy','Senior Secondary Section','NOTA (None of the Above)','','NOTA','Head Boy',99],
  ['nota-senior-head-girl','Senior Secondary Section','NOTA (None of the Above)','','NOTA','Head Girl',99]
].map((c, index) => ({ id:c[0], section:c[1], position:c[5] || 'Section Leader', name:c[2], className:c[3], photoUrl:c[0]==='rayan-mohamed'?'https://i.ibb.co/ym0D1XsJ/1044a44d-bc96-4c4b-9941-3ee76f6fed66.jpg':'', symbolName:c[4], symbolUrl:'', manifesto:c[4]==='NOTA'?'Choose this option if you do not support any listed candidate for this position.':'', audience:'Student', order:c[6] || index + 1, active:true }));
const EMPTY = { id:'', section:'Middle Section', position:'Section Leader', name:'', className:'', photoUrl:'', symbolName:'Microphone', symbolUrl:'', manifesto:'', audience:'Student', order:1, active:true };

export default function ElectionCandidatesAdmin({ analyticsKey }) {
  const [items,setItems]=useState([]), [form,setForm]=useState(EMPTY), [busy,setBusy]=useState(false), [note,setNote]=useState('');
  const refresh = () => loadElectionData().then((x)=>setItems(x.candidates||[])).catch((e)=>setNote(e.message));
  useEffect(()=>{ if(analyticsKey) refresh(); },[analyticsKey]);
  const save = async(e)=>{ e.preventDefault(); setBusy(true); setNote(''); try { const candidate={...form,id:form.id||`${form.name.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')}-${Date.now()}`}; await saveElectionCandidate(analyticsKey,candidate); setForm(EMPTY); await refresh(); setNote('Candidate profile saved.'); } catch(err){setNote(err.message);} finally{setBusy(false);} };
  const seed = async()=>{ if(!window.confirm('Add or update the 13 supplied candidate profiles? Existing photos for matching candidates will be preserved.')) return; setBusy(true); try { const current=new Map(items.map(x=>[x.id,x])); for(const candidate of ROSTER) await saveElectionCandidate(analyticsKey,{...candidate,photoUrl:current.get(candidate.id)?.photoUrl||''}); await refresh(); setNote('Official candidate roster updated. Add each student photo below when ready.'); } catch(e){setNote(e.message);} finally{setBusy(false);} };
  const remove=async(item)=>{if(!window.confirm(`Delete ${item.name}?`))return; setBusy(true); try{await deleteElectionCandidate(analyticsKey,item.id); await refresh();}catch(e){setNote(e.message);}finally{setBusy(false);}};
  return <section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm">
    <div className="flex flex-wrap items-start justify-between gap-3"><div><h3 className="text-lg font-black text-slate-900">Candidate profiles & student photos</h3><p className="mt-2 text-sm font-medium text-slate-500">Candidate photos are managed separately here. Symbol icons are built into the website; an optional custom symbol image URL can override them.</p></div><button type="button" onClick={seed} disabled={!analyticsKey||busy} className="rounded-xl bg-indigo-700 px-4 py-2.5 text-sm font-bold text-white disabled:opacity-50">Load supplied roster</button></div>
    <form onSubmit={save} className="mt-5 grid gap-3 md:grid-cols-2">
      <input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="Candidate name" className="rounded-xl border p-3" />
      <input required value={form.className} onChange={e=>setForm({...form,className:e.target.value})} placeholder="Class (for example 8-C)" className="rounded-xl border p-3" />
      <select value={form.section} onChange={e=>setForm({...form,section:e.target.value,position:e.target.value==='Senior Secondary Section'?'Head Girl':'Section Leader'})} className="rounded-xl border bg-white p-3"><option>Middle Section</option><option>Secondary Section</option><option>Senior Secondary Section</option></select>
      <select value={form.position} onChange={e=>setForm({...form,position:e.target.value})} disabled={form.section!=='Senior Secondary Section'} className="rounded-xl border bg-white p-3 disabled:bg-slate-100">{form.section==='Senior Secondary Section'?<><option>Head Boy</option><option>Head Girl</option></>:<option>Section Leader</option>}</select>
      <select value={form.symbolName} onChange={e=>setForm({...form,symbolName:e.target.value})} className="rounded-xl border bg-white p-3">{ELECTION_SYMBOLS.map(x=><option key={x}>{x}</option>)}</select>
      <label className="md:col-span-2 text-sm font-bold text-slate-700">Student photo URL (separate from symbol)<input type="url" value={form.photoUrl} onChange={e=>setForm({...form,photoUrl:e.target.value})} placeholder="https://.../student-photo.jpg" className="mt-1 w-full rounded-xl border p-3 font-normal" /></label>
      <label className="md:col-span-2 text-sm font-bold text-slate-700">Optional custom symbol image URL<input type="url" value={form.symbolUrl} onChange={e=>setForm({...form,symbolUrl:e.target.value})} placeholder="Leave blank to use the built-in icon" className="mt-1 w-full rounded-xl border p-3 font-normal" /></label>
      <div className="md:col-span-2 flex justify-end gap-2">{form.id&&<button type="button" onClick={()=>setForm(EMPTY)} className="rounded-xl border px-4 py-2.5 font-bold">Cancel</button>}<button disabled={!analyticsKey||busy} className="rounded-xl bg-emerald-600 px-5 py-2.5 font-bold text-white disabled:opacity-50">{busy?'Saving...':form.id?'Update candidate':'Add candidate'}</button></div>
    </form>
    {note&&<p className="mt-3 rounded-xl bg-indigo-50 p-3 text-sm font-bold text-indigo-800">{note}</p>}
    <div className="mt-6 grid gap-3 sm:grid-cols-2">{items.map(item=><article key={item.id} className="flex items-center gap-3 rounded-xl border p-3">{item.photoUrl?<img src={item.photoUrl} alt="" className="h-14 w-14 rounded-lg object-cover"/>:<span className="grid h-14 w-14 place-items-center rounded-lg bg-slate-100 text-slate-400">Photo</span>}<span className="grid h-11 w-11 place-items-center rounded-lg bg-amber-100 text-amber-800"><ElectionSymbolIcon name={item.symbolName} className="h-7 w-7"/></span><div className="min-w-0 flex-1"><strong className="block truncate">{item.name}</strong><small>{item.className} · {item.symbolName}</small></div><button type="button" onClick={()=>setForm({...EMPTY,...item})} className="text-sm font-bold text-indigo-700">Edit</button><button type="button" onClick={()=>remove(item)} className="text-sm font-bold text-red-600">Delete</button></article>)}</div>
  </section>;
}
