export const LEARNING_LABS = [
  {
    slug: 'atl-lab',
    title: 'ATL Lab',
    description: 'The Atal Tinkering Lab encourages students to turn imaginative ideas into working solutions. It provides a creative environment for designing, building, testing, and improving prototypes. Students explore electronics, sensors, mechanical systems, coding, and digital fabrication through practical projects. The lab promotes curiosity by allowing learners to ask questions and investigate possible answers independently. Collaborative challenges teach students how to share responsibilities and learn from different perspectives. Mentors guide learners through the stages of identifying problems, planning solutions, and evaluating results. Projects connect scientific knowledge with challenges found in everyday life and the wider community. The lab also develops patience because successful innovation often requires repeated testing and thoughtful revision. Participation strengthens communication, creativity, critical thinking, and responsible use of technology. ATL helps young innovators gain the confidence to approach the future as capable problem-solvers.'
  },
  {
    slug: 'robotics-lab',
    title: 'Robotics Lab',
    description: 'The Robotics Lab introduces students to machines that can sense, process information, and perform actions. Learners assemble components and discover how mechanical structures work together with electronic controls. Programming activities help students translate logical instructions into visible movement and behaviour. Sensors and motors allow them to investigate navigation, automation, measurement, and responsive systems. Every project develops precision because small design or coding changes can greatly affect a robot’s performance. Team assignments encourage planning, task sharing, respectful discussion, and collaborative troubleshooting. Students learn to examine errors calmly and treat each unsuccessful trial as useful evidence. Robotics connects concepts from mathematics, physics, computing, engineering, and design in a meaningful way. Practical challenges build creativity, spatial reasoning, persistence, and confidence with emerging technology. The lab prepares students to understand and contribute responsibly to an increasingly automated world.'
  },
  {
    slug: 'chemistry-lab',
    title: 'Chemistry Lab',
    description: 'The Chemistry Lab gives students a safe and structured setting for investigating substances and their transformations. Practical sessions help learners connect chemical equations and classroom explanations with observable reactions. Students practise measuring, mixing, heating, filtering, and recording results with care and accuracy. They learn the correct use of glassware, apparatus, protective equipment, and laboratory materials. Safety instructions cultivate responsibility, alertness, and respect for scientific procedures. Guided experiments develop an understanding of properties, acids, bases, salts, gases, and reaction patterns. Learners compare predictions with evidence and discuss why results may differ from expectations. Accurate observation and organised note-taking strengthen analytical thinking and scientific communication. The laboratory also shows how chemistry contributes to health, agriculture, industry, food, and environmental care. These experiences make chemistry relevant while nurturing disciplined and evidence-based inquiry.'
  },
  {
    slug: 'biology-lab',
    title: 'Biology Lab',
    description: 'The Biology Lab enables students to explore living organisms, biological structures, and life processes through direct observation. Microscopes reveal cells and details that cannot be studied clearly with the unaided eye. Models, specimens, slides, and charts help learners understand anatomy, physiology, diversity, and ecological relationships. Practical work develops careful handling, accurate observation, classification, drawing, and recording skills. Students investigate how organisms grow, reproduce, adapt, and interact with their surroundings. Activities encourage respect for life and responsible treatment of biological materials. Experiments connect lessons about plants, animals, microorganisms, health, genetics, and the environment. Learners practise forming questions, comparing samples, interpreting evidence, and presenting conclusions. The laboratory strengthens awareness of biodiversity, conservation, hygiene, nutrition, and public health. Biology becomes a vivid and meaningful subject when students can examine the living world for themselves.'
  },
  {
    slug: 'home-science-lab',
    title: 'Home Science Lab',
    description: 'The Home Science Lab connects academic knowledge with practical skills used in healthy and responsible daily living. Students learn about nutrition, food preparation, hygiene, resource management, textiles, and family well-being. Cooking activities teach accurate measurement, safe handling, cleanliness, planning, and balanced meal preparation. Learners examine how food choices influence growth, energy, health, and long-term wellness. Textile work develops creativity, coordination, patience, and an appreciation of materials and design. Household management tasks encourage thoughtful use of time, money, water, energy, and other resources. Collaborative practical sessions strengthen communication, organisation, responsibility, and mutual respect. The lab also helps students understand consumer awareness, sustainability, child development, and community health. Every activity values dignity of work and equips learners to make informed personal and family decisions. Home Science therefore develops capable, caring, creative, and self-reliant individuals.'
  },
  {
    slug: 'maths-lab',
    title: 'Mathematics Lab',
    description: 'The Mathematics Lab makes abstract ideas easier to understand through models, puzzles, measurements, and hands-on investigation. Students discover patterns and relationships by manipulating objects and testing different strategies. Activities support learning in geometry, algebra, arithmetic, statistics, probability, and spatial reasoning. Visual materials help learners connect symbols and formulas with shapes, quantities, movement, and real situations. Open-ended problems encourage more than one method and promote flexible mathematical thinking. Group tasks give students opportunities to explain reasoning, compare approaches, and learn from mistakes. Measurement projects connect mathematics with architecture, science, finance, art, and everyday decision-making. Games and challenges reduce anxiety while strengthening speed, accuracy, concentration, and logical thought. Learners develop confidence by verifying results through observation and practical demonstration. The lab presents mathematics as an active language for understanding and solving problems in the world.'
  },
  {
    slug: 'computer-lab',
    title: 'Computer Lab',
    description: 'The Computer Lab provides students with guided access to digital tools for learning, communication, research, and creation. Learners develop essential skills in operating systems, document preparation, presentations, spreadsheets, and responsible internet use. Practical sessions improve keyboard proficiency, file organisation, digital communication, and information management. Students learn how to search for reliable information and evaluate online sources critically. Creative assignments allow them to combine text, data, images, audio, and visual design. Teachers emphasise cyber safety, privacy, respectful behaviour, and ethical use of digital resources. Problem-solving tasks build confidence in navigating unfamiliar software and resolving common technical difficulties. Collaborative projects teach students to plan digital work and communicate ideas clearly. The lab supports subjects across the curriculum by making technology a purposeful learning tool. Regular practice prepares learners to participate safely, productively, and confidently in a digital society.'
  },
  {
    slug: 'physics-lab',
    title: 'Physics Lab',
    description: 'The Physics Lab allows students to investigate the principles that govern matter, energy, motion, forces, light, sound, and electricity. Experiments turn theoretical laws into measurable events that learners can observe and analyse. Students practise setting up apparatus, taking readings, controlling variables, and recording data systematically. Accurate measurement teaches precision, patience, and awareness of experimental uncertainty. Learners use graphs and calculations to identify relationships and compare evidence with predictions. Practical tasks connect physics with transport, communication, construction, medicine, energy, and familiar household technologies. Safety routines encourage responsible handling of electrical, optical, mechanical, and thermal equipment. Group experiments develop cooperation, discussion, and shared responsibility for reliable results. Unexpected findings invite students to review methods, detect errors, and refine explanations. The laboratory builds scientific confidence by showing that physical principles can be tested through careful inquiry.'
  },
  {
    slug: 'coding-lab',
    title: 'Coding Lab',
    description: 'The Coding Lab helps students learn how clear instructions can be used to solve problems and create digital experiences. Learners explore algorithms, sequences, conditions, loops, variables, functions, and structured program design. Age-appropriate projects may include stories, games, animations, websites, applications, and automated solutions. Coding activities strengthen logical reasoning by requiring students to break complex challenges into manageable steps. Testing and debugging teach patience, attention to detail, and a positive response to mistakes. Students learn to read code, explain decisions, and improve solutions for clarity and efficiency. Pair and group projects encourage communication, peer learning, planning, and responsible collaboration. Discussions about privacy, fairness, security, and digital impact support ethical technology use. Creative programming connects computing with mathematics, science, art, language, and real community needs. The lab enables students to become confident creators of technology rather than passive users.'
  }
].map((lab, order) => ({ ...lab, order: order + 1, imageUrls: [] }));
